apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
images:
  - name: PROJECT/TODO_APP
    newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/todo-app
    newTag: "4.10"
  - name: PROJECT/TODO_BACKEND
    newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/todo-backend
    newTag: "4.10"
  - name: PROJECT/TODO_GENERATOR
    newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/todo-generator
    newTag: "4.10"
  - name: PROJECT/TODO_BROADCASTER
    newName: asia-northeast3-docker.pkg.dev/dwk-gke-508806/dwk/todo-broadcaster
    newTag: "4.10"
